#!/usr/bin/env ruby

# -------------------------------------------------------------------------- #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

# external dependencies
require 'rubygems'

require 'socket'
require 'base64'
require 'resolv'
require 'ipaddr'

# add local dirs to load path if necessary
lib = File.expand_path(File.join('..', '..', 'lib'), __FILE__)
$LOAD_PATH.unshift(lib) unless $LOAD_PATH.include?(lib)

# add example dirs
examples = File.expand_path(File.join('..'), __FILE__)

# prepare data
udp_socket = UDPSocket.new
result = "SUCCESS"
host_id = 527
data64 = Base64::encode64(File.read(File.join(examples, 'monitoring.data'))).strip.delete("\n")

# send data
udp_socket.send("MONITOR #{result} #{host_id} #{data64}\n", 0, 'localhost', 9000)
